version: "2"

linters:
  default: standard
  enable:
    - revive
    - misspell
    - gocritic

  exclusions:
    rules:
      - path: '_test\.go'
        linters:
          - errcheck

  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - fmt.Printf
        - fmt.Println
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofumpt
    - goimports

  settings:
    gofumpt:
      extra-rules: true
